### ISSUE TITLE
초기 프로젝트를 생성 및 설정한다.

### ISSUE THREAD

**Issue by changhyuns** [f-lab-edu/Ticketing#1]
+ gradle -> kotlin

**Comment by kdhyo** [comment]
- 초기 세팅
    - Groovy Grade -> Kotlin Gradle DSL
    - 디펜던시 추가 목록
        - Spring Web
        - Lombok
        - MySQL Driver
        - Spring Data Redis (Access + Driver)
        - Spring Data JPA
        - Validation
        - Spring Security
    - .gitignore 작성
    - application.properties -> application.yml

**Comment by changhyuns** [comment]
## 체크리스트
- [ ] 필요한 dependency만 추가하였는가 ?
- [ ] dependency 추가에 따른 properties 환경 설정 값을 세팅하였는가 ?
- [ ] 프로젝트 빌드 및 실행은 정상적으로 동작하는가 ?

**Comment by kdhyo** [comment]
- [x] 멀티 모듈 구조
- [x] DB 연결 테스트
- [x] 샘플 API 테스트
- [x] 로깅에 따른 구조 설정
